from typing import Any

class ThreadedConnectionPool:
    def __init__(self, minconn: int, maxconn: int, dsn: str) -> None: ...
    def getconn(self, key: Any | None = None) -> Any: ...
    def putconn(self, conn: Any | None = None, key: Any | None = None, close: bool = False) -> None: ...
    def closeall(self) -> None: ...
